name: Check compilation
on:
  push:
    branches:
      master
jobs:
  compilation:
    runs-on: ubuntu-20.04
    container: epitechcontent/epitest-docker:devel
    steps:
      - name: Checkout
        uses: actions/checkout@v2
